controller_list:
  - name: fake_roam_arm_controller
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_4_joint
      - link_5_joint
      - link_6_joint
      - link_7_joint
initial:  # Define initial robot poses.
  - group: roam_arm
    pose: home_pose