# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: roam_arm
  joint_model_group_pose: home_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - bl_wheel_joint
    - br_wheel_joint
    - fl_wheel_joint
    - fr_wheel_joint
    - link_1_joint
    - link_2_joint
    - link_3_joint
    - link_4_joint
    - link_5_joint
    - link_6_joint
    - link_7_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
roam_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_4_joint
      - link_5_joint
      - link_6_joint
      - link_7_joint
    gains:
        link_1_joint: { p: 100, d: 10, i: 0.1, i_clamp: 0 }
        link_2_joint: { p: 100, d: 10, i: 0.1, i_clamp: 0 }
        link_3_joint: { p: 100, d: 10, i: 0.1, i_clamp: 0 }
        link_4_joint: { p: 100, d: 10, i: 0.1, i_clamp: 0 }
        link_5_joint: { p: 100, d: 10, i: 0.1, i_clamp: 0 }
        link_6_joint: { p: 100, d: 10, i: 0.1, i_clamp: 0 }
        link_7_joint: { p: 100, d: 10, i: 0.1, i_clamp: 0 }
  
    constraints:
        goal_time: 2.0
    state_publish_rate: 25

controller_list:
  - name: roam_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_4_joint
      - link_5_joint
      - link_6_joint
      - link_7_joint
